
export const pagesUnderTest = [
  { name: 'home', path: '/', hasLeadspaceVideo: false },
  { name: 'email-sign-up', path: '/email-sign-up', hasLeadspaceVideo: false },
  { name: 'terms-of-use', path: '/terms-of-use', hasLeadspaceVideo: false },
  { name: 'contact-us', path: '/contact-us', hasLeadspaceVideo: false },
  { name: 'faq', path: '/faq', hasLeadspaceVideo: false },
  { name: 'press', path: '/press', hasLeadspaceVideo: false },
  { name: 'imprint', path: '/imprint', hasLeadspaceVideo: false },
  { name: 'disclaimer', path: '/disclaimer', hasLeadspaceVideo: false },
  { name: 'opt-out-preferences', path: '/opt-out-preferences', hasLeadspaceVideo: false },
  { name: 'products-mini-cream-puffs-38-count', path: '/products/mini-cream-puffs-38-count', hasLeadspaceVideo: false },
  { name: 'products-mini-cream-puffs-50-count', path: '/products/mini-cream-puffs-50-count', hasLeadspaceVideo: false },
  { name: 'products-mini-eclairs-30-count', path: '/products/mini-eclairs-30-count', hasLeadspaceVideo: false },
  { name: 'products-mini-eclairs-50-count', path: '/products/mini-eclairs-50-count', hasLeadspaceVideo: false },
  { name: 'heart-shaped-macarons', path: '/heart-shaped-macarons', hasLeadspaceVideo: false },
  { name: 'products-belgian-chocolate-coconut-macaroons-6-pack', path: '/products/belgian-chocolate-coconut-macaroons-6-pack', hasLeadspaceVideo: false },
  { name: 'products-belgian-chocolate-coconut-macaroons-20-count', path: '/products/belgian-chocolate-coconut-macaroons-20-count', hasLeadspaceVideo: false },
  { name: 'products-belgian-chocolate-coconut-macaroons-24-count', path: '/products/belgian-chocolate-coconut-macaroons-24-count', hasLeadspaceVideo: false },
  { name: 'products-macarons-6-count', path: '/products/macarons-6-count', hasLeadspaceVideo: false },
  { name: 'products-macarons-10-count', path: '/products/macarons-10-count', hasLeadspaceVideo: false },
  { name: 'products-decorated-macarons', path: '/products/decorated-macarons', hasLeadspaceVideo: false },
  { name: 'products-belgian-coconut-macaroons-6-pack', path: '/products/belgian-coconut-macaroons-6-pack', hasLeadspaceVideo: false },
  { name: 'products-belgian-coconut-macaroons-24-count', path: '/products/belgian-coconut-macaroons-24-count', hasLeadspaceVideo: false },
  { name: 'custard-eclairs-4-count', path: '/custard-eclairs-4-count', hasLeadspaceVideo: false },
  { name: 'caramel-eclairs-4-count', path: '/caramel-eclairs-4-count', hasLeadspaceVideo: false },
  { name: 'products', path: '/products', hasLeadspaceVideo: false },
  { name: 'products-macarons-4-count', path: '/products/macarons-4-count', hasLeadspaceVideo: false },
  { name: 'portal', path: '/portal', hasLeadspaceVideo: false },
  { name: 'privacy-policy', path: '/privacy-policy', hasLeadspaceVideo: false },
  { name: 'do-not-sell-or-share-my-personal-information', path: '/do-not-sell-or-share-my-personal-information', hasLeadspaceVideo: false },
  { name: 'new-contact-form', path: '/new-contact-form', hasLeadspaceVideo: false },
 ];